-- Create reviews table for service reviews
CREATE TABLE IF NOT EXISTS reviews (
  REVIEW_ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NULL,
  NAME VARCHAR(100) NOT NULL,
  RATING TINYINT NOT NULL CHECK (RATING BETWEEN 1 AND 5),
  COMMENT TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reviews_user FOREIGN KEY (USER_ID) REFERENCES user(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
